### ISSUE TITLE
[Bug]: Change keypair name

### ISSUE THREAD

**Issue by outscale-vbr** [outscale-dev/cluster-api-provider-outscale#144]
### What happened

for kind test, keypair name is not the same.

### Step to reproduce

  ```
        keypair:
          name: cluster-api
          deleteKeypair: true
        vm:
          clusterName: capo-quickstart
          keypairName: cluster-api-keypair
   ````

### Expected to happen

Have the same name of keypair.

### Add anything

None

### cluster-api output

None

### Environment
```markdown
- Kubernetes version: (use `kubectl version`): v1.22.5-rancher1-1
- OS (e.g. from `/etc/os-release`): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-1160.15.2.el7.x86_64
- cluster-api-provider-outscale version: v1.1.3
- cluster-api version: current
- Install tools: calico, ingress-nginx, osc-ccm
- Kubernetes Distribution: rke
- Kubernetes Distribution version: v1.3.4
```
